// PHASE-4 — static knowledge content types (DATA-007, DATA-008). Rendered from
// data modules only; never generated by an LLM at request time (NFR-005, FR-016).

export type KnowledgeCategory =
  | "git-basics"
  | "git-commands"
  | "branching"
  | "undo"
  | "remote"
  | "github-cli"
  | "github-actions"
  | "github-api"
  | "security"
  | "repo-management"
  | "publishing";

export interface KnowledgeFaq {
  question: string;
  answer: string;
}

export interface GitHubKnowledgeItem {
  slug: string;
  title: string;
  category: KnowledgeCategory;
  age16Summary: string;
  expertExplanation: string;
  syntax?: string;
  copyCommand?: string;
  whenToUse: string[];
  risks: string[];
  commonMistakes?: string[];
  relatedSlugs: string[];
  faq?: KnowledgeFaq[];
}

export type WorkflowDifficulty = "easy" | "medium" | "advanced";
export type WorkflowRisk = "safe" | "careful" | "dangerous";

export type WorkflowCategory =
  | "project-start"
  | "repo-create"
  | "save-changes"
  | "push-pull"
  | "aliases"
  | "forks"
  | "undo"
  | "deployment";

export interface WorkflowCommand {
  label: string;
  code: string;
  copyable: boolean;
}

export interface CommandWorkflow {
  slug: string;
  title: string;
  goal: string;
  difficulty: WorkflowDifficulty;
  category: WorkflowCategory;
  shortExplanation: string;
  commands: WorkflowCommand[];
  whenToUse: string;
  commonMistakes: string[];
  riskLevel: WorkflowRisk;
  relatedCommands: string[];
}

export interface TerminalShortcut {
  slug: string;
  title: string;
  description: string;
  command: string;
  category: "alias" | "navigation" | "inspect" | "productivity";
}
